# Generated by Django 6.1.1 on 2026-09-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('asset',), name='unique_active_checkout_per_asset'),
        ),
    ]
